import gql from 'graphql-tag';
// import Test from '../assets/header/CTDC_Logo.svg';

// The ideal image size of landingPageHero 1400x600px
// Tile1 Tile2 Tile3 images 293x349 px
// Tile4 image optimum size 600x 436 px
export const landingPageData = {
  callToActionTitle: 'Enabling secure, scalable storage and sharing of cancer data',
  callToActionDescription: 'A data repository in the Cancer Research Data Commons ($$[CRDC](https://datacommons.cancer.gov/)$$) ecosystem for storing and sharing data generated by NCI funded programs. The CDS provides secure and authorized storage and data sharing capabilities in the cloud for studies that are not a good match for submission to other CRDC repositories. The CDS will host cancer data of all types including genomic, proteomic, and imaging data. ',
  callToActionButtonText: 'EXPLORE CDS DATA',
  callToActionLink: '/data',
  heroLeftBg: {
    alt: 'Alt tag1',
    img: 'https://raw.githubusercontent.com/CBIIT/datacommons-assets/main/cds/landing/LeftSide.png',
  },
  heroRightBg: {
    alt: 'Alt tag1',
    img: 'https://raw.githubusercontent.com/CBIIT/datacommons-assets/main/cds/landing/RightSide.png',
  },
  landingPageHero: {
    alt: 'Alt tag1',
    img: 'https://raw.githubusercontent.com/CBIIT/datacommons-assets/main/cds/landing/landingPageHero.png',
  },
  landingPageTile: {
    alt: 'Alt tag1',
    img: 'https://raw.githubusercontent.com/CBIIT/datacommons-assets/main/cds/landing/tilesBackgroundGrid.png',
  },
  landingPageStatsBar: [
    {
      statTitle: 'Studies',
      statAPI: 'numberOfStudies',
      callToActionLink: '/studies',
    },
    {
      statTitle: 'participants',
      statAPI: 'numberOfSubjects',
      callToActionLink: '/data',
    },
    {
      statTitle: 'samples',
      statAPI: 'numberOfSamples',
      callToActionLink: '/data',
    },
    {
      statTitle: 'files',
      statAPI: 'numberOfFiles',
      callToActionLink: '/data',
    },
  ],
  tile1: {
    alt: '',
    img: 'https://raw.githubusercontent.com/CBIIT/datacommons-assets/main/cds/landing/landingTile1.png',
    titleText: 'ABOUT THE CANCER DATA SERVICE',
    descriptionText: 'The Cancer Data Service (CDS) is a data repository under the Cancer Research Data Commons ($$[CRDC](https://datacommons.cancer.gov/)$$) infrastructure for storing cancer research data generated by NCI funded programs. The CDS provides secure and authorized storage and data sharing capabilities in the cloud for studies that are not a good match for other CRDC repositories.',
    callToActionText: 'Explore',
    callToActionLink: '/data', // This links to the "About" static page.
  },
  tile2: {
    alt: '',
    img: 'https://raw.githubusercontent.com/CBIIT/datacommons-assets/main/cds/landing/landingTile2.png',
    titleText: 'STUDIES',
    descriptionText: 'View summaries of the studies within CDS.',
    callToActionText: 'Go to studies listing',
    callToActionLink: '/studies', // This links to the studies Listing Page.
  },
  tile3: {
    alt: '',
    img: 'https://raw.githubusercontent.com/CBIIT/datacommons-assets/main/cds/landing/landingTile3.png',
    titleText: 'CLICK HERE TO GET STARTED',
    descriptionText: 'Click to Get Started or reach out to the CDS Helpdesk for any information.',
    callToActionText: 'Start the process',
    callToActionLink: '/datasubmit', // Link to the "Submit" Static Page
  },
  tile4: {
    alt: '',
    img: 'https://raw.githubusercontent.com/CBIIT/datacommons-assets/main/cds/landing/landingTile4.png',
    titleText: 'CDS DATA',
    descriptionText: 'Search all CDS cases and build cohorts from the studies hosted in the CDS. The data files from these cohorts can then be analyzed in an NCI Cloud Resource.',
    callToActionText: 'Learn More',
    callToActionLink: '/cancerDataService', // This links to the cases dashboard.
  },
};

// --------------- GraphQL query - Retrieve Landing page data --------------
export const GET_LANDING_PAGE_DATA_QUERY = gql`{
  searchSubjects{
    numberOfFiles
    numberOfSamples
    numberOfStudies
    numberOfSubjects
} 
  }
  `;
